# Generated by Django 4.1.3 on 2022-12-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='skip_counter',
            field=models.BooleanField(default=False),
        ),
    ]
