# Generated by Django 4.1.3 on 2022-12-09 18:35

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_product_options_product_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color_code',
            field=colorfield.fields.ColorField(choices=[('#FFFFFF', 'white'), ('#add8e6', 'blue'), ('#f9ead7', 'lightorange'), ('#e6e6f9', 'lightblue'), ('#fef0f5', 'yellow'), ('#ffb6c1', 'red'), ('#faefe6', 'lightred'), ('#ffe4e1', 'green'), ('#f5f5f5', 'gray'), ('#eff8ff', 'lightblue2')], default='white', image_field=None, max_length=18, samples=None),
        ),
    ]
