# Generated by Django 4.1.3 on 2022-12-09 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_product_color_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color_code',
            field=models.TextField(null=True),
        ),
    ]
