# Generated by Django 4.1.3 on 2022-12-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_product_color_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
